### ISSUE TITLE
"Unable to load file" when the exe in a Chinese name :(

### ISSUE THREAD

**Issue by zhuangya** [atom/rcedit#17]
![2016-05-19 6 38 35](https://cloud.githubusercontent.com/assets/499038/15390896/ef7ef816-1df0-11e6-8776-b14ee0982cfd.png)

as the screenshot said:

i tried to edit a electron-built exe by `rcedit`, but i get "Unable to load file" if the filename is in Chinese.

and then i rename the exe to `ep.exe`,  `rcedit` stop complaining.

any idea?

thanks in advanced.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/384

**Comment by zhuangya** [comment]
ok thank you @develar 
and i will keep an eye on that issue

**Comment by develar** [comment]
@zhuangya sorry, I mean that it's not only your issue, it is critical issue for a lot of users. Please reopen.

**Comment by develar** [comment]
Any chance to get answer from project maintainers ;)?

**Comment by towertop** [comment]
Still having this problem in version 0.5.0 .

**Comment by changkun** [comment]
Is here any find a alternative solution?

Still having this problem.

**Comment by develar** [comment]
@changkun I remember that I should fix it in the electron-builder, fix will be in several days.

**Comment by develar** [comment]
Good news — I found issue and fix it. electron-builder will be released soon.

**Comment by changkun** [comment]
@develar excellent job!

**Comment by zcbenz** [comment]
Closed with #23.
