### ISSUE TITLE
Change file description and copyright?

### ISSUE THREAD

**Issue by szwacz** [atom/rcedit#2]
Hello, could this tool also allow people to change file description and copyright strings?
![screen shot 2015-05-06 at 05 53 33](https://cloud.githubusercontent.com/assets/4573903/7487284/02de157a-f3b5-11e4-9ba8-697baeaaec2d.png)

**Comment by Ivshti** [comment]
I would like to add the product name to this list.

**Comment by Ivshti** [comment]
It ChangeString does what I think it does implementing this will be straight forward. Will PR later today if thats the case.

**Comment by Ivshti** [comment]
I couldn't set up my windows building environment (what a pain), so I am leaving this for now.

**Comment by jden** [comment]
(tagging https://github.com/maxogden/electron-packager/issues/30 so that the status on this issue is reflected on that thread)

**Comment by felicienfrancois** [comment]
this works for me:
```
$ rcedit "path-to-exe-or-dll" --set-version-string "CompanyName" "MyCompany"
$ rcedit "path-to-exe-or-dll" --set-version-string "FileDescription" "This is an exe"
$ rcedit "path-to-exe-or-dll" --set-version-string "LegalCopyright" "Copyright whatever"
$ rcedit "path-to-exe-or-dll" --set-version-string "ProductName" "MyAwesomeProduct"
```

this is just a documentation issue

**Comment by szwacz** [comment]
Doh! Looks like you are right @felicienfrancois

**Comment by Aluxian** [comment]
Thanks @felicienfrancois. Seriously, this should be documented!
