### ISSUE TITLE
Port to linux ?

### ISSUE THREAD

**Issue by MisterDA** [atom/rcedit#4]
Hi !
Is there a way to port this to linux ? I see it depends on windows.h, but perhaps there would be a way to use rcedit on linux without any windows dependencies ?

I'd like to set an icon to an exe file, usually I go with ResHacker and Wine. I'd like to use rcedit instead. I think I must use Wine on linux, but if there was another way or if rcedit could be portable, please let me know.

**Comment by zcbenz** [comment]
Rcedit relies on some win32 APIs to edit the `exe`s, it doesn't have code to parse `exe` itself.
