### ISSUE TITLE
Compilation fails with error RC1015 when MFC was not installed with Visual Studio

### ISSUE THREAD

**Issue by geary** [atom/rcedit#5]
`rcedit.rc` has this include:

    #include "afxres.h"

The `afxres.h` header is part of MFC, so if Visual Studio is installed without the MFC option, rcedit does not compile.

Because rcedit does not actually use MFC, the fix is simply to change the include to:

    #include <windows.h>

PR will be on its way in a few minutes...

**Comment by zcbenz** [comment]
Fixed by #7.
