### ISSUE TITLE
File version and product version fields are erroneously truncated to 8 bits

### ISSUE THREAD

**Issue by geary** [atom/rcedit#6]
The file version and product version fields in a PE executable are 64-bit values, each consisting of four 16-bit unsigned values.

rcedit erroneously truncates these 16-bit values to 8 bits when the `--set-file-version` or `--set-product-version` switches are used. For example, a version number `12345.6789.9876.5432` is changed to `57.133.148.56`.

This is the root cause of [Squirrel issue 545](https://github.com/Squirrel/Squirrel.Windows/issues/545) and any similar issues in other products that use rcedit.

PR on its way in a moment...

**Comment by lee-dohm** [comment]
@paulcbetts since you're the one that made the assertion in https://github.com/Squirrel/Squirrel.Windows/issues/545#issuecomment-169385040 that the version fields are 8-bit, is this a 32-bit executable versus 64-bit executable thing?

**Comment by paulcbetts** [comment]
Citation Needed? I'm not sure I believe you

**Comment by geary** [comment]
Both 32-bit and 64-bit executables use the same format for these version resources: a 64-bit value containing four 16-bit fields.

I tested this patch using the updated rcedit.exe with a Squirrel build. The Setup.exe file that Squirrel generates is a 32-bit executable, and the patch works fine with it.

**Comment by geary** [comment]
For reference, the code that actually sets these values in rcedit is in `rescle.cc` lines [215-216](https://github.com/atom/rcedit/blob/master/src/rescle.cc#L215) and [241-242](https://github.com/atom/rcedit/blob/master/src/rescle.cc#L241). Both are the same code:

    root->dwProductVersionMS = v1 << 16 | v2;
    root->dwProductVersionLS = v3 << 16 | v4;

The `dwProductVersionMS` and `dwProductVersionLS` fields are defined in `verrsrc.h`:

    DWORD   dwProductVersionMS;     /* e.g. 0x00030010 = "3.10" */
    DWORD   dwProductVersionLS;     /* e.g. 0x00000031 = "0.31" */

**Comment by geary** [comment]
And here's the [MSDN reference](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058%28v=vs.85%29.aspx) while I'm at it. :-)

> FILEVERSION version
> Binary version number for the file. The version consists of two 32-bit integers, defined by four 16-bit integers. For example, "FILEVERSION 3,10,0,61" is translated into two doublewords: 0x0003000a and 0x0000003d, in that order. Therefore, if version is defined by the DWORD values dw1 and dw2, they need to appear in the FILEVERSION statement as follows: HIWORD(dw1), LOWORD(dw1), HIWORD(dw2), LOWORD(dw2).
>
> PRODUCTVERSION version
> Binary version number for the product with which the file is distributed. The version parameter is two 32-bit integers, defined by four 16-bit integers. For more information about version, see the FILEVERSION description.

**Comment by paulcbetts** [comment]
Nice!

**Comment by zcbenz** [comment]
Fixed by #7.
